name: my-infosec-awesome

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test with awesome_bot
      run: |
        gem install awesome_bot
        awesome_bot README.md --white-list LICENSE,emailrep.io,"github.com/pe3zx/my-infosec-awesome/actions","cape.contextis.com/submit/","iot.newskysecurity.com","www.phishingfrenzy.com","tuts4you.com/download.php?list.17","illuminatejs.com" --allow-ssl --allow-redirect --allow 429
